project:
  alias: k8s-ruby

# Slack channel in Chef Software slack to send notifications about build failures, etc
slack:
  notify_channel:
    - inspec-notify

github:
  delete_branch_on_merge: true
  version_tag_format: v{{version}}

# pipelines:
#  - verify:
#     trigger: pull_request
#     description: Pull Request validation tests

rubygems:
  - k8s-ruby

release_branches:
    - main:
        version_constraint: "*"

subscriptions:
  - workload: pull_request_merged:{{github_repo}}:{{release_branch}}:*
    actions:
      # we pull the latest tags from `k8s-ruby/k8s-ruby` hence we don't bump version here.
      # But we build and publish gems from here
      - built_in:build_gem
  - workload: project_promoted:{{agent_id}}:*
    actions:
      - built_in:publish_rubygems
